/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TravelSearchResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: SearchResults;
};
export interface KeyboardEvent {
    key: string;
    metaKey: boolean;
    altKey: boolean;
    ctrlKey: boolean;
    shiftKey: boolean;
    keyCode: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TravelSearchParams {
    departure_city: string;
    departure_date: string;
    return_date: string;
    num_travelers: number;
    destination_city: string;
}
export interface Flight {
    cabinClass: string;
    isDirect: boolean;
    baggageAllowance: number;
    arrivalTime: string;
    flightNumber: string;
    cancellationPolicy: string;
    departureTime: string;
    pricePerPerson: number;
    amenities: Array<string>;
    layovers: Array<Layover>;
    durationMinutes: number;
    airline: string;
}
export interface Layover {
    durationMinutes: number;
    airport: string;
}
export interface SearchResults {
    cost_breakdown: CostBreakdown;
    top_accommodations: Array<Accommodation>;
    packages: Array<Package>;
    departure_city: string;
    available_flights: Array<Flight>;
    currency: string;
    destination_city: string;
    available_dates: Array<string>;
    price_range: string;
}
export interface BookingSession {
    userName: string;
    userEmail: string;
    openedSarahAI: boolean;
    postSarahSatisfaction: boolean;
    packagePrice: number;
    initialSatisfaction: boolean;
    destinationCity: string;
    sourceCity: string;
    currency: string;
    proceededToBooking: boolean;
    timestamp: Time;
}
export interface Package {
    flight: Flight;
    accommodation: Accommodation;
    amenities: Array<string>;
    totalPrice: number;
}
export interface SearchHistory {
    destination: string;
    departure_date: string;
    return_date: string;
    timestamp: Time;
    num_travelers: number;
    departure: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AIResponse {
    personality: string;
    message: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type OutcallResult = {
    __kind__: "error";
    error: OutcallError;
} | {
    __kind__: "success";
    success: string;
};
export interface CostBreakdown {
    total_accommodation_cost: number;
    total_flight_cost: number;
    accommodation_cost_per_night: number;
    flight_cost_per_person: number;
    total_cost: number;
    night_count: number;
    person_count: number;
}
export type AnonymousSearchKey = string;
export interface Accommodation {
    contactInfo: string;
    starRating: number;
    reviews: Array<Review>;
    cancellationPolicy: string;
    pricePerNight: number;
    name: string;
    amenities: Array<string>;
    guestRating: number;
    address: string;
    breakfastIncluded: boolean;
    distanceToAirportKm: number;
    roomType: string;
}
export interface Review {
    date: string;
    reviewerName: string;
    comment: string;
    rating: number;
}
export interface UserProfile {
    name: string;
    email?: string;
    preferences?: string;
}
export enum OutcallError {
    invalid_city_name = "invalid_city_name",
    outcall_failed = "outcall_failed",
    api_limit_exceeded = "api_limit_exceeded",
    invalid_url = "invalid_url",
    invalid_api_key = "invalid_api_key",
    no_credentials_found = "no_credentials_found"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllSearchHistory(): Promise<Array<[Principal, Array<SearchHistory>]>>;
    getAnonymousSearchHistory(key: AnonymousSearchKey): Promise<Array<SearchHistory> | null>;
    getBookingAnalytics(): Promise<Array<BookingSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDepartureCities(): Promise<Array<string>>;
    getDestinationCities(): Promise<Array<string>>;
    getDummyOutcall(): Promise<OutcallResult>;
    getHotels(_params: TravelSearchParams): Promise<Array<Accommodation>>;
    getSarahResponse(userInput: string): Promise<AIResponse>;
    getSearchHistory(): Promise<Array<SearchHistory>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleKeyboardEvent(_event: KeyboardEvent): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    recordBookingConversion(is_user: boolean, user_id: string, userName: string, userEmail: string, sourceCity: string, destinationCity: string, packagePrice: number, currency: string, initialSatisfaction: boolean, openedSarahAI: boolean, postSarahSatisfaction: boolean, proceededToBooking: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTravelOptions(params: TravelSearchParams): Promise<TravelSearchResult>;
    setApiKey(key: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCurrencyMapping(): Promise<void>;
    validateAdminCredentials(suppliedUsername: string, suppliedPassword: string): Promise<boolean>;
}
import type { OutcallError as _OutcallError, OutcallResult as _OutcallResult, SearchHistory as _SearchHistory, SearchResults as _SearchResults, TravelSearchResult as _TravelSearchResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllSearchHistory(): Promise<Array<[Principal, Array<SearchHistory>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSearchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSearchHistory();
            return result;
        }
    }
    async getAnonymousSearchHistory(arg0: AnonymousSearchKey): Promise<Array<SearchHistory> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnonymousSearchHistory(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnonymousSearchHistory(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingAnalytics(): Promise<Array<BookingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartureCities(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartureCities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartureCities();
            return result;
        }
    }
    async getDestinationCities(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestinationCities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestinationCities();
            return result;
        }
    }
    async getDummyOutcall(): Promise<OutcallResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getDummyOutcall();
                return from_candid_OutcallResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDummyOutcall();
            return from_candid_OutcallResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotels(arg0: TravelSearchParams): Promise<Array<Accommodation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotels(arg0);
            return result;
        }
    }
    async getSarahResponse(arg0: string): Promise<AIResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getSarahResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSarahResponse(arg0);
            return result;
        }
    }
    async getSearchHistory(): Promise<Array<SearchHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSearchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSearchHistory();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleKeyboardEvent(arg0: KeyboardEvent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.handleKeyboardEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleKeyboardEvent(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordBookingConversion(arg0: boolean, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number, arg7: string, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBookingConversion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBookingConversion(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTravelOptions(arg0: TravelSearchParams): Promise<TravelSearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTravelOptions(arg0);
                return from_candid_TravelSearchResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTravelOptions(arg0);
            return from_candid_TravelSearchResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApiKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCurrencyMapping(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrencyMapping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrencyMapping();
            return result;
        }
    }
    async validateAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_OutcallError_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OutcallError): OutcallError {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OutcallResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OutcallResult): OutcallResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TravelSearchResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TravelSearchResult): TravelSearchResult {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_SearchHistory>]): Array<SearchHistory> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    preferences: [] | [string];
}): {
    name: string;
    email?: string;
    preferences?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email)),
        preferences: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.preferences))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: _OutcallError;
} | {
    success: string;
}): {
    __kind__: "error";
    error: OutcallError;
} | {
    __kind__: "success";
    success: string;
} {
    return "error" in value ? {
        __kind__: "error",
        error: from_candid_OutcallError_n12(_uploadFile, _downloadFile, value.error)
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalid_city_name: null;
} | {
    outcall_failed: null;
} | {
    api_limit_exceeded: null;
} | {
    invalid_url: null;
} | {
    invalid_api_key: null;
} | {
    no_credentials_found: null;
}): OutcallError {
    return "invalid_city_name" in value ? OutcallError.invalid_city_name : "outcall_failed" in value ? OutcallError.outcall_failed : "api_limit_exceeded" in value ? OutcallError.api_limit_exceeded : "invalid_url" in value ? OutcallError.invalid_url : "invalid_api_key" in value ? OutcallError.invalid_api_key : "no_credentials_found" in value ? OutcallError.no_credentials_found : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: _SearchResults;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: SearchResults;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    preferences?: string;
}): {
    name: string;
    email: [] | [string];
    preferences: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        preferences: value.preferences ? candid_some(value.preferences) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
