/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIResponse { 'personality' : string, 'message' : string }
export interface Accommodation {
  'contactInfo' : string,
  'starRating' : number,
  'reviews' : Array<Review>,
  'cancellationPolicy' : string,
  'pricePerNight' : number,
  'name' : string,
  'amenities' : Array<string>,
  'guestRating' : number,
  'address' : string,
  'breakfastIncluded' : boolean,
  'distanceToAirportKm' : number,
  'roomType' : string,
}
export type AnonymousSearchKey = string;
export interface BookingSession {
  'userName' : string,
  'userEmail' : string,
  'openedSarahAI' : boolean,
  'postSarahSatisfaction' : boolean,
  'packagePrice' : number,
  'initialSatisfaction' : boolean,
  'destinationCity' : string,
  'sourceCity' : string,
  'currency' : string,
  'proceededToBooking' : boolean,
  'timestamp' : Time,
}
export interface CostBreakdown {
  'total_accommodation_cost' : number,
  'total_flight_cost' : number,
  'accommodation_cost_per_night' : number,
  'flight_cost_per_person' : number,
  'total_cost' : number,
  'night_count' : number,
  'person_count' : number,
}
export interface Flight {
  'cabinClass' : string,
  'isDirect' : boolean,
  'baggageAllowance' : number,
  'arrivalTime' : string,
  'flightNumber' : string,
  'cancellationPolicy' : string,
  'departureTime' : string,
  'pricePerPerson' : number,
  'amenities' : Array<string>,
  'layovers' : Array<Layover>,
  'durationMinutes' : number,
  'airline' : string,
}
export interface KeyboardEvent {
  'key' : string,
  'metaKey' : boolean,
  'altKey' : boolean,
  'ctrlKey' : boolean,
  'shiftKey' : boolean,
  'keyCode' : bigint,
}
export interface Layover { 'durationMinutes' : number, 'airport' : string }
export type OutcallError = { 'invalid_city_name' : null } |
  { 'outcall_failed' : null } |
  { 'api_limit_exceeded' : null } |
  { 'invalid_url' : null } |
  { 'invalid_api_key' : null } |
  { 'no_credentials_found' : null };
export type OutcallResult = { 'error' : OutcallError } |
  { 'success' : string };
export interface Package {
  'flight' : Flight,
  'accommodation' : Accommodation,
  'amenities' : Array<string>,
  'totalPrice' : number,
}
export interface Review {
  'date' : string,
  'reviewerName' : string,
  'comment' : string,
  'rating' : number,
}
export interface SearchHistory {
  'destination' : string,
  'departure_date' : string,
  'return_date' : string,
  'timestamp' : Time,
  'num_travelers' : number,
  'departure' : string,
}
export interface SearchResults {
  'cost_breakdown' : CostBreakdown,
  'top_accommodations' : Array<Accommodation>,
  'packages' : Array<Package>,
  'departure_city' : string,
  'available_flights' : Array<Flight>,
  'currency' : string,
  'destination_city' : string,
  'available_dates' : Array<string>,
  'price_range' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TravelSearchParams {
  'departure_city' : string,
  'departure_date' : string,
  'return_date' : string,
  'num_travelers' : number,
  'destination_city' : string,
}
export type TravelSearchResult = { 'error' : string } |
  { 'success' : SearchResults };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'preferences' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSearchHistory' : ActorMethod<
    [],
    Array<[Principal, Array<SearchHistory>]>
  >,
  'getAnonymousSearchHistory' : ActorMethod<
    [AnonymousSearchKey],
    [] | [Array<SearchHistory>]
  >,
  'getBookingAnalytics' : ActorMethod<[], Array<BookingSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepartureCities' : ActorMethod<[], Array<string>>,
  'getDestinationCities' : ActorMethod<[], Array<string>>,
  'getDummyOutcall' : ActorMethod<[], OutcallResult>,
  'getHotels' : ActorMethod<[TravelSearchParams], Array<Accommodation>>,
  'getSarahResponse' : ActorMethod<[string], AIResponse>,
  'getSearchHistory' : ActorMethod<[], Array<SearchHistory>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleKeyboardEvent' : ActorMethod<[KeyboardEvent], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordBookingConversion' : ActorMethod<
    [
      boolean,
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTravelOptions' : ActorMethod<[TravelSearchParams], TravelSearchResult>,
  'setApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCurrencyMapping' : ActorMethod<[], undefined>,
  'validateAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];