/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SearchHistory = IDL.Record({
  'destination' : IDL.Text,
  'departure_date' : IDL.Text,
  'return_date' : IDL.Text,
  'timestamp' : Time,
  'num_travelers' : IDL.Float64,
  'departure' : IDL.Text,
});
export const AnonymousSearchKey = IDL.Text;
export const BookingSession = IDL.Record({
  'userName' : IDL.Text,
  'userEmail' : IDL.Text,
  'openedSarahAI' : IDL.Bool,
  'postSarahSatisfaction' : IDL.Bool,
  'packagePrice' : IDL.Float64,
  'initialSatisfaction' : IDL.Bool,
  'destinationCity' : IDL.Text,
  'sourceCity' : IDL.Text,
  'currency' : IDL.Text,
  'proceededToBooking' : IDL.Bool,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'preferences' : IDL.Opt(IDL.Text),
});
export const OutcallError = IDL.Variant({
  'invalid_city_name' : IDL.Null,
  'outcall_failed' : IDL.Null,
  'api_limit_exceeded' : IDL.Null,
  'invalid_url' : IDL.Null,
  'invalid_api_key' : IDL.Null,
  'no_credentials_found' : IDL.Null,
});
export const OutcallResult = IDL.Variant({
  'error' : OutcallError,
  'success' : IDL.Text,
});
export const TravelSearchParams = IDL.Record({
  'departure_city' : IDL.Text,
  'departure_date' : IDL.Text,
  'return_date' : IDL.Text,
  'num_travelers' : IDL.Float64,
  'destination_city' : IDL.Text,
});
export const Review = IDL.Record({
  'date' : IDL.Text,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Float64,
});
export const Accommodation = IDL.Record({
  'contactInfo' : IDL.Text,
  'starRating' : IDL.Float64,
  'reviews' : IDL.Vec(Review),
  'cancellationPolicy' : IDL.Text,
  'pricePerNight' : IDL.Float64,
  'name' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'guestRating' : IDL.Float64,
  'address' : IDL.Text,
  'breakfastIncluded' : IDL.Bool,
  'distanceToAirportKm' : IDL.Float64,
  'roomType' : IDL.Text,
});
export const AIResponse = IDL.Record({
  'personality' : IDL.Text,
  'message' : IDL.Text,
});
export const KeyboardEvent = IDL.Record({
  'key' : IDL.Text,
  'metaKey' : IDL.Bool,
  'altKey' : IDL.Bool,
  'ctrlKey' : IDL.Bool,
  'shiftKey' : IDL.Bool,
  'keyCode' : IDL.Int,
});
export const CostBreakdown = IDL.Record({
  'total_accommodation_cost' : IDL.Float64,
  'total_flight_cost' : IDL.Float64,
  'accommodation_cost_per_night' : IDL.Float64,
  'flight_cost_per_person' : IDL.Float64,
  'total_cost' : IDL.Float64,
  'night_count' : IDL.Float64,
  'person_count' : IDL.Float64,
});
export const Layover = IDL.Record({
  'durationMinutes' : IDL.Float64,
  'airport' : IDL.Text,
});
export const Flight = IDL.Record({
  'cabinClass' : IDL.Text,
  'isDirect' : IDL.Bool,
  'baggageAllowance' : IDL.Float64,
  'arrivalTime' : IDL.Text,
  'flightNumber' : IDL.Text,
  'cancellationPolicy' : IDL.Text,
  'departureTime' : IDL.Text,
  'pricePerPerson' : IDL.Float64,
  'amenities' : IDL.Vec(IDL.Text),
  'layovers' : IDL.Vec(Layover),
  'durationMinutes' : IDL.Float64,
  'airline' : IDL.Text,
});
export const Package = IDL.Record({
  'flight' : Flight,
  'accommodation' : Accommodation,
  'amenities' : IDL.Vec(IDL.Text),
  'totalPrice' : IDL.Float64,
});
export const SearchResults = IDL.Record({
  'cost_breakdown' : CostBreakdown,
  'top_accommodations' : IDL.Vec(Accommodation),
  'packages' : IDL.Vec(Package),
  'departure_city' : IDL.Text,
  'available_flights' : IDL.Vec(Flight),
  'currency' : IDL.Text,
  'destination_city' : IDL.Text,
  'available_dates' : IDL.Vec(IDL.Text),
  'price_range' : IDL.Text,
});
export const TravelSearchResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : SearchResults,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSearchHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(SearchHistory)))],
      ['query'],
    ),
  'getAnonymousSearchHistory' : IDL.Func(
      [AnonymousSearchKey],
      [IDL.Opt(IDL.Vec(SearchHistory))],
      ['query'],
    ),
  'getBookingAnalytics' : IDL.Func([], [IDL.Vec(BookingSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartureCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDestinationCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDummyOutcall' : IDL.Func([], [OutcallResult], []),
  'getHotels' : IDL.Func(
      [TravelSearchParams],
      [IDL.Vec(Accommodation)],
      ['query'],
    ),
  'getSarahResponse' : IDL.Func([IDL.Text], [AIResponse], ['query']),
  'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistory)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handleKeyboardEvent' : IDL.Func([KeyboardEvent], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordBookingConversion' : IDL.Func(
      [
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTravelOptions' : IDL.Func(
      [TravelSearchParams],
      [TravelSearchResult],
      [],
    ),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCurrencyMapping' : IDL.Func([], [], []),
  'validateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SearchHistory = IDL.Record({
    'destination' : IDL.Text,
    'departure_date' : IDL.Text,
    'return_date' : IDL.Text,
    'timestamp' : Time,
    'num_travelers' : IDL.Float64,
    'departure' : IDL.Text,
  });
  const AnonymousSearchKey = IDL.Text;
  const BookingSession = IDL.Record({
    'userName' : IDL.Text,
    'userEmail' : IDL.Text,
    'openedSarahAI' : IDL.Bool,
    'postSarahSatisfaction' : IDL.Bool,
    'packagePrice' : IDL.Float64,
    'initialSatisfaction' : IDL.Bool,
    'destinationCity' : IDL.Text,
    'sourceCity' : IDL.Text,
    'currency' : IDL.Text,
    'proceededToBooking' : IDL.Bool,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'preferences' : IDL.Opt(IDL.Text),
  });
  const OutcallError = IDL.Variant({
    'invalid_city_name' : IDL.Null,
    'outcall_failed' : IDL.Null,
    'api_limit_exceeded' : IDL.Null,
    'invalid_url' : IDL.Null,
    'invalid_api_key' : IDL.Null,
    'no_credentials_found' : IDL.Null,
  });
  const OutcallResult = IDL.Variant({
    'error' : OutcallError,
    'success' : IDL.Text,
  });
  const TravelSearchParams = IDL.Record({
    'departure_city' : IDL.Text,
    'departure_date' : IDL.Text,
    'return_date' : IDL.Text,
    'num_travelers' : IDL.Float64,
    'destination_city' : IDL.Text,
  });
  const Review = IDL.Record({
    'date' : IDL.Text,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const Accommodation = IDL.Record({
    'contactInfo' : IDL.Text,
    'starRating' : IDL.Float64,
    'reviews' : IDL.Vec(Review),
    'cancellationPolicy' : IDL.Text,
    'pricePerNight' : IDL.Float64,
    'name' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'guestRating' : IDL.Float64,
    'address' : IDL.Text,
    'breakfastIncluded' : IDL.Bool,
    'distanceToAirportKm' : IDL.Float64,
    'roomType' : IDL.Text,
  });
  const AIResponse = IDL.Record({
    'personality' : IDL.Text,
    'message' : IDL.Text,
  });
  const KeyboardEvent = IDL.Record({
    'key' : IDL.Text,
    'metaKey' : IDL.Bool,
    'altKey' : IDL.Bool,
    'ctrlKey' : IDL.Bool,
    'shiftKey' : IDL.Bool,
    'keyCode' : IDL.Int,
  });
  const CostBreakdown = IDL.Record({
    'total_accommodation_cost' : IDL.Float64,
    'total_flight_cost' : IDL.Float64,
    'accommodation_cost_per_night' : IDL.Float64,
    'flight_cost_per_person' : IDL.Float64,
    'total_cost' : IDL.Float64,
    'night_count' : IDL.Float64,
    'person_count' : IDL.Float64,
  });
  const Layover = IDL.Record({
    'durationMinutes' : IDL.Float64,
    'airport' : IDL.Text,
  });
  const Flight = IDL.Record({
    'cabinClass' : IDL.Text,
    'isDirect' : IDL.Bool,
    'baggageAllowance' : IDL.Float64,
    'arrivalTime' : IDL.Text,
    'flightNumber' : IDL.Text,
    'cancellationPolicy' : IDL.Text,
    'departureTime' : IDL.Text,
    'pricePerPerson' : IDL.Float64,
    'amenities' : IDL.Vec(IDL.Text),
    'layovers' : IDL.Vec(Layover),
    'durationMinutes' : IDL.Float64,
    'airline' : IDL.Text,
  });
  const Package = IDL.Record({
    'flight' : Flight,
    'accommodation' : Accommodation,
    'amenities' : IDL.Vec(IDL.Text),
    'totalPrice' : IDL.Float64,
  });
  const SearchResults = IDL.Record({
    'cost_breakdown' : CostBreakdown,
    'top_accommodations' : IDL.Vec(Accommodation),
    'packages' : IDL.Vec(Package),
    'departure_city' : IDL.Text,
    'available_flights' : IDL.Vec(Flight),
    'currency' : IDL.Text,
    'destination_city' : IDL.Text,
    'available_dates' : IDL.Vec(IDL.Text),
    'price_range' : IDL.Text,
  });
  const TravelSearchResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : SearchResults,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSearchHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(SearchHistory)))],
        ['query'],
      ),
    'getAnonymousSearchHistory' : IDL.Func(
        [AnonymousSearchKey],
        [IDL.Opt(IDL.Vec(SearchHistory))],
        ['query'],
      ),
    'getBookingAnalytics' : IDL.Func([], [IDL.Vec(BookingSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartureCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDestinationCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDummyOutcall' : IDL.Func([], [OutcallResult], []),
    'getHotels' : IDL.Func(
        [TravelSearchParams],
        [IDL.Vec(Accommodation)],
        ['query'],
      ),
    'getSarahResponse' : IDL.Func([IDL.Text], [AIResponse], ['query']),
    'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistory)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handleKeyboardEvent' : IDL.Func([KeyboardEvent], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordBookingConversion' : IDL.Func(
        [
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTravelOptions' : IDL.Func(
        [TravelSearchParams],
        [TravelSearchResult],
        [],
      ),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCurrencyMapping' : IDL.Func([], [], []),
    'validateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };